### ISSUE TITLE
BadImageFormat exception while loading tdjson.dll

### ISSUE THREAD

**Issue by Sergey-Terekhin** [egramtel/egram.tel#1]
Hi!
I've tried to compile and run client under Windows 10 x64 and got BadImageFormat exception here:
```CSharp
services.AddSingleton(p =>
{
  Client.Log.SetVerbosityLevel(5); //<-- here
  Client.Log.SetFilePath(Path.Combine(p.GetService<Storage>().LogDirectory, "tdlib.log"));
  return new Client();
});
```

Stack trace:
```
   at TD.Bindings.WindowsBindings.td_set_log_verbosity_level(Int32 level)
   at Egram.Registry.TDRegistry.<>c.<AddTDLib>b__0_0(IServiceProvider p) in C:\Users\terekhin\sources\egram.tel\Egram\Registry\TDRegistry.cs:line 15
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Egram.Program.Run(IServiceProvider provider) in C:\Users\terekhin\sources\egram.tel\Egram\Program.cs:line 41
   at Egram.Program.Main(String[] args) in C:\Users\terekhin\sources\egram.tel\Egram\Program.cs:line 18
```

I've tried both x64 and x86 builds but result is the same. I think, some dependency for `tdjson.dll` is missed and can not be loaded

**Comment by Anseltis** [comment]
I confirm that problem is still actual for windows 10 x64.

**Comment by kirsan31** [comment]
You need tdlib itself :) See https://github.com/x2bool/tdsharp.

**Comment by x2bool** [comment]
Seems like a broken version of tdjson.dll. I don't have a Windows machine. Could you please help me out? Please try to unpack one of the following libs into https://github.com/x2bool/egram.tel/tree/master/Egram and run it again.

https://yadi.sk/d/4GO4w5-q3VUiWX

https://yadi.sk/d/thBukU4h3VUiaf

**Comment by kirsan31** [comment]
@x2bool same error in all 3 cases.

**Comment by schroding3rscat** [comment]
I managed to fix this by building https://github.com/x2bool/tdsharp and replacing existing TDLib in the `Egram` folder. I also took pre-built `tdjson.dll` from https://yadi.sk/d/thBukU4h3VUiaf provided by @x2bool.

**Comment by x2bool** [comment]
Alright everyone, sorry for inconvenience. tdjson.dll in the repo is broken. We are going to fix this with proper NuGet packaging.

@schroding3rscat Why had you had to compile https://github.com/x2bool/tdsharp yourself? Is there anything wrong with version from NuGet?

**Comment by x2bool** [comment]
Temporary workaround for Windows: https://github.com/x2bool/egram.tel/commit/5b2385cd7e6775919445af100f36f14c0388d9f9

Please checkout the latest version from master.

**Comment by kirsan31** [comment]
It works now, thanks.

**Comment by Sergey-Terekhin** [comment]
Confirm, it works, thanks

**Comment by schroding3rscat** [comment]
@x2bool, I think I had mixed up. My bad.
