### ISSUE TITLE
SetDpiAwareness error

### ISSUE THREAD

**Issue by vladimirzenin** [egramtel/egram.tel#41]
Windows 7.
When compiling [the project](https://github.com/egramtel/egram.tel), an error occurs:

D:\egram.tel\application\Tel.Egram>dotnet run

Unhandled Exception: System.TypeInitializationException: The type initializer fo
r 'Avalonia.Win32.Win32Platform' threw an exception. ---> System.EntryPointNotFo
undException: Unable to find an entry point named 'SetProcessDpiAwarenessContext
' in DLL 'user32.dll'.
   at Avalonia.Win32.Interop.UnmanagedMethods.SetProcessDpiAwarenessContext(IntP
tr dpiAWarenessContext)
   at Avalonia.Win32.Win32Platform.SetDpiAwareness()
   at Avalonia.Win32.Win32Platform..ctor()
   at Avalonia.Win32.Win32Platform..cctor()
   --- End of inner exception stack trace ---
   at Avalonia.Win32.Win32Platform.Initialize(Boolean deferredRendering)
   at Avalonia.Controls.AppBuilderBase`1.Setup() in D:\a\1\s\src\Avalonia.Contro
ls\AppBuilderBase.cs:line 273
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextPr
ovider) in D:\a\1\s\src\Avalonia.Controls\AppBuilderBase.cs:line 122
   at Tel.Egram.Program.Run(ServiceCollection services, IServiceProvider provide
r) in D:\egram.tel\application\Tel.Egram\Program.cs:line 76
   at Tel.Egram.Program.Main(String[] args) in D:\egram.tel\application\Tel.Egra
m\Program.cs:line 23

**Comment by x2bool** [comment]
@vladimirzenin could you please provider some details here: https://github.com/AvaloniaUI/Avalonia/issues/2095
