### ISSUE TITLE
using phone numbers without the prefix crashes the application

### ISSUE THREAD

**Issue by glennawatson** [egramtel/egram.tel#45]
Initially when I started using the application I used my phone number without the international prefix. So 415000000 -- so North American phone number. 

Then second try I worked out what was going on and put the +1 prefix in front. 

Other applications often list all the prefixes at the front with country flags. Long term that might be a good fix, short term catch the exception and show a error to the user.

Thanks :)

```
Application: Tel.Egram.exe
CoreCLR Version: 4.6.26919.2
Description: The process was terminated due to an unhandled exception.
Exception Info: ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> TdLib.ErrorException: PHONE_NUMBER_INVALID
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass0_0.<.cctor>b__2() in D:\a\1\s\src\ReactiveUI\RxApp.cs:line 64
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Simple.cs:line 83
   at Avalonia.Threading.AvaloniaScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   at ReactiveUI.RxApp.<>c.<.cctor>b__0_1(Exception ex) in D:\a\1\s\src\ReactiveUI\RxApp.cs:line 68
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 46
   at System.Reactive.ScheduledObserver`1.Run(Object state, Action`1 recurse) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ScheduledObserver.cs:line 254
   at System.Reactive.Concurrency.Scheduler.InvokeRec1[TState](IScheduler scheduler, Pair`2 pair) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Recursive.cs:line 89
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass2_1`1.<Schedule>b__1()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Application.Run(Window mainWindow)
   at Tel.Egram.Program.Run(IDependencyResolver resolver) in D:\a\1\s\src\Tel.Egram\Program.cs:line 72
   at Tel.Egram.Program.Main(String[] args) in D:\a\1\s\src\Tel.Egram\Program.cs:line 18
```

**Comment by x2bool** [comment]
Thanks for reporting. Yes, users sometimes encounter this behaviour, it's not obvious that you have to put prefix in front of the phone number. Many things in Egram have incomplete or initial implementation at this stage. But I am going to prioritize this now since users often report this.

**Comment by x2bool** [comment]
<img width="263" alt="image" src="https://user-images.githubusercontent.com/892945/52166844-95148780-2723-11e9-9431-cb0b700943ca.png">

Last build has this dropdown with county codes and phone mask. Closing this for now. Thanks for the idea.
