### ISSUE TITLE
Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'tdjson' or one of its dependencies.

### ISSUE THREAD

**Issue by denisgolius** [egramtel/egram.tel#55]
version - egram-0.5.297

```
 uname -a
Linux think 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux

 cat /etc/*release
DISTRIB_ID=Debian
DISTRIB_RELEASE=19.01
DISTRIB_CODENAME=testing
DISTRIB_DESCRIPTION="Netrunner 19.01"
NAME="Netrunner"
VERSION_ID="19.01"
VERSION="19.01 (Blackbird)"
ID=netrunner
ID_LIKE=debian
HOME_URL="http://www.netrunner.com/"
SUPPORT_URL="http://forum.netrunner-os.com/"
BUG_REPORT_URL="https://github.com/netrunner/netrunner-feedback"
VERSION_CODENAME=testing
PRETTY_NAME="Netrunner 19.01 - Blackbird"
```

```
./Tel.Egram

Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'tdjson' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libtdjson: cannot open shared object file: No such file or directory
   at TdLib.Bindings.LinuxBindings.td_set_log_file_path(IntPtr path)
   at TdLib.Client.Log.SetFilePath(String path)
   at Tel.Egram.Registry.<>c__DisplayClass1_0.<AddTdLib>b__0() in /home/vsts/work/1/s/src/Tel.Egram/Registry.cs:line 48
   at Splat.DependencyResolverMixins.<>c__DisplayClass8_0`1.<RegisterLazySingleton>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Splat.DependencyResolverMixins.GetService[T](IDependencyResolver This, String contract)
   at Tel.Egram.Registry.<>c__DisplayClass1_0.<AddTdLib>b__1() in /home/vsts/work/1/s/src/Tel.Egram/Registry.cs:line 55
   at Splat.DependencyResolverMixins.<>c__DisplayClass8_0`1.<RegisterLazySingleton>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Splat.DependencyResolverMixins.GetService[T](IDependencyResolver This, String contract)
   at Tel.Egram.Registry.<>c__DisplayClass1_0.<AddTdLib>b__3() in /home/vsts/work/1/s/src/Tel.Egram/Registry.cs:line 68
   at Splat.DependencyResolverMixins.<>c__DisplayClass8_0`1.<RegisterLazySingleton>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Splat.DependencyResolverMixins.GetService[T](IDependencyResolver This, String contract)
   at Tel.Egram.Registry.<>c__DisplayClass3_0.<AddServices>b__13() in /home/vsts/work/1/s/src/Tel.Egram/Registry.cs:line 213
   at Splat.DependencyResolverMixins.<>c__DisplayClass8_0`1.<RegisterLazySingleton>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Splat.DependencyResolverMixins.GetService[T](IDependencyResolver This, String contract)
   at Tel.Egram.Model.Application.AuthenticationLogic.BindAuthentication(MainWindowModel model) in /home/vsts/work/1/s/src/Tel.Egram.Model/Application/AuthenticationLogic.cs:line 20
   at Tel.Egram.Model.Application.MainWindowModel.<.ctor>b__28_0(CompositeDisposable disposables) in /home/vsts/work/1/s/src/Tel.Egram.Model/Application/MainWindowModel.cs:line 32
   at ReactiveUI.ViewForMixins.<>c__DisplayClass3_0.<WhenActivated>b__0() in D:\a\1\s\src\ReactiveUI\Activation\ViewForMixins.cs:line 74
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Reactive.Disposables.CompositeDisposable..ctor(IEnumerable`1 disposables) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Disposables\CompositeDisposable.cs:line 67
   at ReactiveUI.ViewModelActivator.Activate() in D:\a\1\s\src\ReactiveUI\Activation\ViewModelActivator.cs:line 84
   at Tel.Egram.Program.Run(IDependencyResolver resolver) in /home/vsts/work/1/s/src/Tel.Egram/Program.cs:line 77
   at Tel.Egram.Program.Main(String[] args) in /home/vsts/work/1/s/src/Tel.Egram/Program.cs:line 17
Аварийный останов

```

**Comment by ForNeVeR** [comment]
The libtdjson version I'm building for egram.tel does not seem to be compatible with Debian for some reason. If you have any idea how to fix that, you're welcome to https://github.com/ForNeVeR/tdlib.native

**Comment by x2bool** [comment]
Yep :(

Majority of people with this problem come from Debian.

**Comment by ForNeVeR** [comment]
I would very much appreciate if somebody could research this problem. What exactly is failing for them? Which dependency?
