### ISSUE TITLE
 System.MissingMethodException: Method not found: 'System.Span`1 on Windows

### ISSUE THREAD

**Issue by Alexey-2016** [egramtel/egram.tel#9]
Unhandled Exception: System.MissingMethodException: Method not found: 'System.Span`1<!!1> System.MemoryExtensions.NonPortableCast(System.Span`1<!!0>)'.
   at SixLabors.ImageSharp.Memory.ArrayPoolMemoryManager.Buffer`1.get_Span()
   at SixLabors.ImageSharp.Memory.ArrayPoolMemoryManager.Allocate[T](Int32 length, Boolean clear)
   at SixLabors.ImageSharp.Memory.MemoryManagerExtensions.Allocate2D[T](MemoryManager memoryManager, Int32 width, Int32 height, Boolean clear)
   at SixLabors.ImageSharp.ImageFrame`1..ctor(MemoryManager memoryManager, Int32 width, Int32 height, ImageFrameMetaData metaData)
   at SixLabors.ImageSharp.ImageFrameCollection`1..ctor(Image`1 parent, Int32 width, Int32 height)
   at SixLabors.ImageSharp.Image`1..ctor(Configuration configuration, Int32 width, Int32 height, ImageMetaData metadata)
   at SixLabors.ImageSharp.Image`1..ctor(Int32 width, Int32 height)
   at Egram.Components.Graphics.AvatarLoader.<>c__DisplayClass9_0.<CreateFallbackAvatar>b__0() in C:\Users\IEUser\Downloads\egram.tel-master\egram.tel-master\Egram.Components\Graphics\AvatarLoader.cs:line 155
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Egram.Components.Graphics.AvatarLoader.LoadForChatAsync(Chat chat, Size size, Boolean forceFallback) in C:\Users\IEUser\Downloads\egram.tel-master\egram.tel-master\Egram.Components\Graphics\AvatarLoader.cs:line 91
   at Egram.Components.Navigation.SegmentInteractor.<FetchAll>b__6_0(IObserver`1 observer) in C:\Users\IEUser\Downloads\egram.tel-master\egram.tel-master\Egram.Components.Navigation\SegmentInteractor.cs:line 165
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.ScheduledObserver`1.Run(Object state, Action`1 recurse)
   at System.Reactive.Concurrency.Scheduler.InvokeRec1[TState](IScheduler scheduler, Pair`2 pair)
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass2_1`1.<Schedule>b__1()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Egram.Program.Run(IServiceProvider provider) in C:\Users\IEUser\Downloads\egram.tel-master\egram.tel-master\Egram\Program.cs:line 44
   at Egram.Program.Main(String[] args) in C:\Users\IEUser\Downloads\egram.tel-master\egram.tel-master\Egram\Program.cs:line 18

**Comment by x2bool** [comment]
Hi! This repo is a bit outdated and has many issues. Please wait a little bit before I publish new version

**Comment by x2bool** [comment]
Everything should be ok now. Feel free to reopen if it does not work.
